### ISSUE TITLE
Forcing element state

### ISSUE THREAD

**Issue by ollie-iterators** [w3c/webdriver-bidi#344] opened 2022-12-13 17:32 UTC
I was wondering if it would be possible to force an element into a specific element state without using the developer tools on a browser.

Forcing element states is done in the browser by:
If you right click on an element in the browser (Chrome or FireFox), and click Inspect, then you will go to the developer tools. There will be an option visible on the screen called ":hov" which is near the text saying "Filter Styles". It allows you to force the element into a certain state. The states that the element can be forced to are: :hover, :active, :focus, :focus-visible, :focus-within, :visited, :target.

In Safari, you can right click on the element, press Inspect Element, which again goes to the developer tools. Right clicking on the code for an element shows a button in the user interface that says Change pseudo class. The pseudo classes that it can change to are the same as the ones for Chrome and FireFox

**Comment by whimboo** [comment] 2022-12-13 19:35
Please do not file new issues for existing ones. This is a dupe of #249.

**Closed by whimboo** 2022-12-13 19:35 UTC

**Comment by ollie-iterators** [comment] 2022-12-14 14:22
You know that #249 is a closed issue

**Comment by whimboo** [comment] 2022-12-15 13:17
It's closed but with a reason. And there is no need to file a separate issue about the exact same topic.
